version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mydb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d testdb"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: myapp
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: testdb
      DB_USER: user
      DB_PASS: pass
    command: pytest -v